import { useMemo, useState } from "react";
import { useReducedMotion } from "motion/react";
import { Activity, ArrowDownLeft, ArrowUpRight, Info, ShieldCheck, Sun, Thermometer } from "lucide-react";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Area, Bar, CartesianGrid, Cell, ComposedChart, Line, Pie, PieChart, ReferenceArea, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "@/lib/recharts";
import type { AnalysisResult, EnergyBalancePoint } from "@/lib/thermal-types";

const LOSS_SERIES = [
  ["walls_out", "Walls", "#fb923c"], ["roof_out", "Roof", "#38bdf8"],
  ["floor_out", "Floor", "#a3b18a"], ["openings_out", "Openings", "#fb7185"],
  ["ventilation_out", "Ventilation", "#2dd4bf"], ["bridges_out", "Bridges", "#cbd5e1"],
] as const;
const tipStyle = { background: "#101b25", border: "1px solid rgba(255,255,255,.15)", borderRadius: 12, fontSize: 11, color: "#cbd5e1" };
const axisTick = { fill: "#94a3b8", fontSize: 10 };
const fmt = (value: number) => value.toFixed(2);

export function ModelEvidence({ result }: { result: AnalysisResult }) {
  const info = result.model_info;
  if (!info) return <div className="mb-5 rounded-xl border border-amber-300/20 bg-amber-300/5 p-4" data-testid="legacy-model-notice"><p className="text-sm text-amber-100" data-testid="legacy-model-title">Legacy study · original results preserved</p><p className="mt-2 text-xs leading-6 text-slate-400" data-testid="legacy-model-description">These stored temperatures, material choices, and metrics have not been recalculated. Run a new study to use the expanded catalogue and version 2 heat balance. Legacy pathway estimates may not sum to the recorded total.</p></div>;
  return <div className="mb-5 rounded-xl border border-sky-300/20 bg-[#0c1821]/90" data-testid="model-evidence-panel">
    <div className="flex flex-col justify-between gap-3 p-4 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="rounded-lg bg-sky-300/10 p-2 text-sky-200"><Activity size={18} /></span><div><p className="text-sm text-sky-100" data-testid="model-version-label">{info.version} · energy-balance model</p><p className="mt-1 text-[11px] text-slate-400" data-testid="model-validation-status">Uncalibrated screening model · reference properties, not certified performance</p></div></div><span className="font-mono text-[10px] text-slate-400" data-testid="model-timestep">{info.timestep_seconds / 60}-minute solve / hourly output</span></div>
    <details className="border-t border-white/10" data-testid="model-assumptions-details"><summary className="cursor-pointer px-4 py-3 text-xs text-sky-200 transition-colors hover:bg-sky-300/5" data-testid="model-assumptions-toggle">Inspect assumptions, material references & validation limits</summary><div className="space-y-5 px-4 pb-5">
      <div className="grid gap-4 sm:grid-cols-4">{[["wall-u", "Wall U", `${info.wall_u_value.toFixed(3)} W/m²K`], ["roof-u", "Roof U", `${info.roof_u_value.toFixed(3)} W/m²K`], ["capacity", "Effective storage", `${info.heat_capacity_kj_k.toFixed(0)} kJ/K`], ["density", "Air density", `${info.air_density_kg_m3.toFixed(3)} kg/m³`]].map(([id,label,value]) => <div key={id} className="rounded-lg bg-white/[.025] p-3"><p className="text-[10px] text-slate-500" data-testid={`model-${id}-label`}>{label}</p><p className="mt-1 font-mono text-xs text-slate-200" data-testid={`model-${id}-value`}>{value}</p></div>)}</div>
      <div><h3 className="mb-2 text-xs font-semibold text-slate-200" data-testid="model-equations-title">Method & assumptions</h3><ul className="list-disc space-y-2 pl-4 text-xs leading-6 text-slate-400">{info.assumptions.map((note,i)=><li key={note} data-testid={`model-assumption-${i}`}>{note}</li>)}</ul></div>
      <div className="rounded-lg border border-amber-300/10 bg-amber-300/5 p-4"><h3 className="mb-2 text-xs font-semibold text-amber-100" data-testid="model-limitations-title">What these numbers cannot establish</h3><ul className="list-disc space-y-2 pl-4 text-xs leading-6 text-slate-400">{info.limitations.map((note,i)=><li key={note} data-testid={`model-limitation-${i}`}>{note}</li>)}</ul></div>
      <div><h3 className="mb-3 text-xs font-semibold text-slate-200" data-testid="model-snapshots-title">Material properties captured with this run</h3><div className="space-y-3">{info.material_snapshots.map(material=><div key={material.id} className="rounded-lg border border-white/10 p-3" data-testid={`model-snapshot-${material.id}`}><p className="text-xs text-slate-200" data-testid={`model-snapshot-values-${material.id}`}>{material.label} · λ {material.conductivity_w_m_k} W/m·K · ρ {material.density_kg_m3} kg/m³ · cₚ {material.specific_heat_j_kg_k} J/kg·K</p><p className="mt-2 text-[11px] leading-5 text-slate-500" data-testid={`model-snapshot-basis-${material.id}`}>{material.property_basis}</p><a href={material.source_url} target="_blank" rel="noopener noreferrer" className="mt-2 inline-block text-[11px] text-sky-300 underline" data-testid={`model-source-${material.id}`}>Reference / background ↗</a></div>)}</div></div>
    </div></details>
  </div>;
}

function EnergyBalance({ result }: { result: AnalysisResult }) {
  const points = result.energy_balance ?? [];
  const [view,setView] = useState<"hourly"|"cumulative">("hourly");
  const [selectedHour,setSelectedHour] = useState(Math.min(12,points.length-1));
  const reducedMotion = useReducedMotion();
  const selected = points[Math.max(0,Math.min(selectedHour,points.length-1))];
  const chart = useMemo(() => {
    const sums: Record<string,number> = {};
    return points.map(point=>{
      const values: Record<string,number|string> = {label:point.label};
      const fields = ["solar_in","internal_in","ambient_in","storage_change", ...LOSS_SERIES.map(([key])=>key)] as (keyof EnergyBalancePoint)[];
      for (const key of fields) {
        const raw = Number(point[key]);
        sums[key] = (sums[key] ?? 0)+raw;
        const value = view === "cumulative" ? sums[key] : raw;
        values[key] = key.endsWith("_out") ? -value : value;
      }
      return values;
    });
  },[points,view]);
  if (!selected) return null;
  const gain = selected.solar_in + selected.internal_in + selected.ambient_in;
  const loss = LOSS_SERIES.reduce((sum,[key])=>sum+selected[key],0);
  return <Card className="workspace-card mt-6 overflow-hidden border-sky-300/20" data-testid="heat-balance-card"><CardHeader className="flex-col justify-between gap-4 border-b border-white/10 sm:flex-row"><div><CardDescription className="font-mono text-[10px] uppercase tracking-[.17em]" data-testid="heat-balance-eyebrow">The energy ledger / kWh</CardDescription><CardTitle className="mt-2 font-heading text-2xl" data-testid="heat-balance-title">Every gain. Every loss. In balance.</CardTitle><p className="mt-2 text-xs leading-6 text-slate-400" data-testid="heat-balance-description">Gains rise above zero. Losses fall below. The white line is the change in stored thermal energy.</p></div><div className="flex shrink-0 gap-1 rounded-lg border border-white/10 p-1" data-testid="heat-balance-view-controls">{(["hourly","cumulative"] as const).map(mode=><Button key={mode} variant="ghost" size="sm" aria-pressed={view===mode} onClick={()=>setView(mode)} className={`text-xs capitalize ${view===mode?"bg-sky-300/10 text-sky-100":"text-slate-500"}`} data-testid={`heat-balance-${mode}-button`}>{mode}</Button>)}</div></CardHeader><CardContent className="pt-5">
    <div className="mb-4 flex flex-wrap gap-x-4 gap-y-2 text-[10px] text-slate-400" data-testid="heat-balance-legend">{[["solar_in","Solar","#fbbf24"],["ambient_in","Ambient/ground gains","#60a5fa"],["internal_in","Internal gains","#a3e635"],...LOSS_SERIES,["storage_change","Stored energy Δ","#f8fafc"]].map(([id,name,color])=><span key={id} className="inline-flex items-center gap-1.5" data-testid={`heat-balance-legend-${id}`}><i className="h-2 w-2 rounded-sm" style={{backgroundColor:color}} />{name}</span>)}</div>
    <div className="h-[340px] w-full" data-testid="heat-balance-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chart} stackOffset="sign" margin={{top:12,right:8,left:0,bottom:5}}><CartesianGrid stroke="rgba(148,163,184,.09)" vertical={false}/><XAxis dataKey="label" tick={axisTick} axisLine={false} tickLine={false} interval={Math.max(0,Math.floor(points.length/5)-1)}/><YAxis tick={axisTick} width={45} axisLine={false} tickLine={false}/><Tooltip contentStyle={tipStyle} formatter={(value:number,name:string)=>[`${value.toFixed(3)} kWh`,name]}/><ReferenceLine y={0} stroke="#64748b"/><ReferenceLine x={selected.label} stroke="#e2e8f0" strokeDasharray="3 5"/><Bar dataKey="solar_in" name="Solar gain" stackId="energy" fill="#fbbf24" isAnimationActive={!reducedMotion}/><Bar dataKey="ambient_in" name="Ambient/ground gain" stackId="energy" fill="#60a5fa" isAnimationActive={!reducedMotion}/><Bar dataKey="internal_in" name="Internal gain" stackId="energy" fill="#a3e635" isAnimationActive={!reducedMotion}/>{LOSS_SERIES.map(([key,name,color])=><Bar key={key} dataKey={key} name={`${name} loss`} stackId="energy" fill={color} isAnimationActive={!reducedMotion}/>)}<Line dataKey="storage_change" name="Stored energy change" type="linear" stroke="#f8fafc" strokeWidth={2} dot={false} isAnimationActive={!reducedMotion}/></ComposedChart></ResponsiveContainer></div>
    <p className="mt-2 text-[10px] text-slate-500" data-testid="heat-balance-view-caption">{view==="hourly"?"Energy during each one-hour interval, not instantaneous power.":"Running energy totals from the start of the simulation, not instantaneous power."}</p>
    <div className="mt-6 grid gap-6 border-t border-white/10 pt-5 lg:grid-cols-[1fr_1fr]">
      <div><div className="flex items-center justify-between gap-3"><LabelHour label={selected.label}/><span className="font-mono text-[10px] text-slate-500" data-testid="heat-balance-hour-number">Hour {selected.hour+1} / {points.length}</span></div><input aria-label="Inspect simulation hour" type="range" min={0} max={points.length-1} value={selectedHour} onChange={event=>setSelectedHour(Number(event.target.value))} className="control-range mt-4" data-testid="heat-balance-hour-slider"/>
        <div className="mt-5 space-y-3">{LOSS_SERIES.map(([key,name,color])=><div key={key} className="flex items-center gap-3" data-testid={`balance-hour-loss-${key}`}><span className="w-24 shrink-0 text-xs text-slate-400">{name}</span><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full transition-[width] duration-300" style={{width:`${loss>0?selected[key]/loss*100:0}%`,backgroundColor:color}}/></div><span className="w-20 text-right font-mono text-[11px] text-slate-300">{fmt(selected[key])} kWh</span></div>)}</div>
      </div>
      <div className="rounded-xl border border-white/10 bg-[#08121a] p-4" data-testid="heat-balance-hour-inspector"><div className="grid grid-cols-3 gap-3 text-center"><div><ArrowDownLeft className="mx-auto text-amber-300" size={18}/><p className="mt-2 text-[10px] uppercase tracking-wide text-slate-500" data-testid="balance-gain-label">Energy in</p><p className="mt-2 font-mono text-xl text-amber-200" data-testid="balance-hour-gain">{fmt(gain)}</p></div><div><Thermometer className="mx-auto text-slate-200" size={18}/><p className="mt-2 text-[10px] uppercase tracking-wide text-slate-500" data-testid="balance-storage-label">Stored Δ</p><p className="mt-2 font-mono text-xl text-slate-100" data-testid="balance-hour-storage">{selected.storage_change>=0?"+":""}{fmt(selected.storage_change)}</p></div><div><ArrowUpRight className="mx-auto text-sky-300" size={18}/><p className="mt-2 text-[10px] uppercase tracking-wide text-slate-500" data-testid="balance-loss-label">Energy out</p><p className="mt-2 font-mono text-xl text-sky-200" data-testid="balance-hour-loss">{fmt(loss)}</p></div></div>
        <svg viewBox="0 0 360 55" className="mt-3 w-full" aria-hidden="true"><path d="M35 28 H140 M220 28 H325" stroke="#254458" strokeWidth="2"/><path d="M35 28 H140" stroke="#fbbf24" strokeWidth="2" strokeDasharray="5 12" className={gain>0?"thermal-flow":""}/><path d="M220 28 H325" stroke="#38bdf8" strokeWidth="2" strokeDasharray="5 12" className={loss>0?"thermal-flow":""}/><rect x="146" y="8" width="68" height="40" rx="8" fill="#172735" stroke="#57809a"/><path d="M161 31 L180 17 L199 31 M165 29 V40 H195 V29" fill="none" stroke="#bfd7e4"/></svg>
        <p className="text-center text-[11px] text-slate-400" data-testid="balance-equation">Energy in − energy out = stored energy change · kWh</p><div className="mt-4 border-t border-white/10 pt-3"><p className="flex items-center gap-2 text-xs text-emerald-200" data-testid="balance-numerical-closure"><ShieldCheck size={13}/> Numerical closure: {Math.abs(selected.balance_error)<.000001?"< 0.000001":Math.abs(selected.balance_error).toFixed(6)} kWh</p><p className="mt-2 text-[10px] leading-5 text-slate-500" data-testid="balance-closure-disclaimer">Equation closure checks arithmetic only. It does not demonstrate real-world prediction accuracy. Values above are rounded for display.</p></div>
      </div>
    </div>
  </CardContent></Card>;
}

function LabelHour({label}:{label:string}) { return <p className="font-heading text-base text-slate-200" data-testid="heat-balance-selected-hour">Hour inspector · {label}</p>; }

export default function ThermalCharts({ result }: { result: AnalysisResult }) {
  const reducedMotion = useReducedMotion();
  const [showSensitivity,setShowSensitivity] = useState(false);
  const chart = result.chart_data.map((point,index)=>({...point,range:result.sensitivity?.[index]?[result.sensitivity[index].low,result.sensitivity[index].high]:undefined}));
  const pathways = result.heat_flows.filter(flow=>flow.value>0);
  const pathwayTotal = pathways.reduce((sum,flow)=>sum+flow.value,0);
  return <>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.65fr)_minmax(280px,.75fr)]">
      <Card className="workspace-card" data-testid="temperature-chart-card"><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardDescription className="font-mono text-[10px] uppercase tracking-[.14em]" data-testid="temperature-chart-eyebrow">{result.inputs.duration_hours} hour thermal response / {result.inputs.location}</CardDescription><CardTitle className="mt-2 font-heading text-xl" data-testid="temperature-chart-title">Inside vs ambient temperature</CardTitle></div>{Boolean(result.sensitivity?.length) && <Button variant="outline" size="sm" aria-pressed={showSensitivity} onClick={()=>setShowSensitivity(!showSensitivity)} className="border-sky-300/20 text-[10px] text-sky-200" data-testid="temperature-sensitivity-toggle">{showSensitivity?"Hide":"Show"} sensitivity</Button>}</div><div className="mt-3 flex flex-wrap gap-4 text-[10px] text-slate-400"><span data-testid="chart-legend-inside">● <span className="text-orange-200">Inside · interval end</span></span><span data-testid="chart-legend-ambient">┄ Ambient · hourly mean</span><span className="text-emerald-300/70" data-testid="chart-legend-comfort">▧ 18–26 °C target</span></div></CardHeader><CardContent>
        <div className="h-[310px] w-full" data-testid="temperature-line-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chart} margin={{top:8,right:8,left:-5,bottom:5}}><CartesianGrid stroke="rgba(148,163,184,.09)" vertical={false}/><XAxis dataKey="label" tick={axisTick} interval={Math.max(0,Math.floor(chart.length/4)-1)} axisLine={false} tickLine={false}/><YAxis tick={axisTick} unit="°" axisLine={false} tickLine={false}/><ReferenceArea y1={18} y2={26} fill="#34d399" fillOpacity={.055} strokeOpacity={0} ifOverflow="extendDomain"/><Tooltip contentStyle={tipStyle}/>{showSensitivity && <Area type="linear" dataKey="range" name="Illustrative sensitivity (°C)" stroke="none" fill="#38bdf8" fillOpacity={.14} isAnimationActive={!reducedMotion}/>}<Line type="linear" dataKey="inside_temp" name="Inside °C" stroke="#fb923c" strokeWidth={3} dot={false} activeDot={{r:5}} isAnimationActive={!reducedMotion}/><Line type="linear" dataKey="ambient_temp" name="Ambient °C" stroke="#38bdf8" strokeWidth={1.6} strokeDasharray="5 5" dot={false} isAnimationActive={!reducedMotion}/></ComposedChart></ResponsiveContainer></div>
        <div className="mt-3 flex flex-wrap justify-between gap-2 border-t border-white/10 pt-3"><span className="text-[11px] text-slate-400" data-testid="temperature-chart-caption">Air-temperature target, not full thermal-comfort certification</span><span className="font-mono text-xs text-orange-200" data-testid="average-temperature">avg {result.average_inside_temp.toFixed(1)}°C inside</span></div>
        {showSensitivity && <p className="mt-3 rounded-lg bg-sky-300/5 p-3 text-[11px] leading-6 text-slate-400" data-testid="temperature-sensitivity-disclaimer">Envelope of two ±20% heat-transfer/solar-input perturbations plus the base case. Illustrative sensitivity only—not a confidence interval or validated accuracy range.</p>}
      </CardContent></Card>
      <Card className="workspace-card" data-testid="heat-flow-card"><CardHeader><CardDescription className="font-mono text-[10px] uppercase tracking-[.14em]" data-testid="heat-flow-eyebrow">Where warmth leaves / kWh</CardDescription><CardTitle className="font-heading text-xl" data-testid="heat-flow-title">Heat-loss pathways</CardTitle></CardHeader><CardContent>
        <div className="relative h-[185px]" data-testid="heat-loss-donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pathways} dataKey="value" nameKey="name" innerRadius={60} outerRadius={83} paddingAngle={pathways.length>1?3:0} stroke="none" isAnimationActive={!reducedMotion}>{pathways.map(flow=><Cell key={flow.name} fill={flow.color}/>)}</Pie><Tooltip contentStyle={tipStyle} formatter={(value:number,name:string)=>[`${value.toFixed(3)} kWh`,name]}/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><p className="font-mono text-2xl text-slate-100" data-testid="heat-loss-pathway-total">{fmt(pathwayTotal)}</p><p className="mt-1 text-[9px] uppercase tracking-widest text-slate-500" data-testid="heat-loss-total-unit">kWh · pathways</p></div></div>
        <div className="mt-2 space-y-3">{result.heat_flows.map((flow,index)=><div key={flow.name} className="flex items-center justify-between gap-3 text-xs" data-testid={`heat-flow-row-${index}`}><span className="inline-flex items-center gap-2 text-slate-400"><i className="h-2 w-2 rounded-full" style={{backgroundColor:flow.color}}/>{flow.name}</span><span className="font-mono text-slate-200" data-testid={`heat-flow-value-${index}`}>{fmt(flow.value)} <span className="text-[10px] text-slate-500">{pathwayTotal>0?Math.round(flow.value/pathwayTotal*100):0}%</span></span></div>)}</div>
        <p className="mt-5 text-[10px] leading-5 text-slate-500" data-testid="heat-flow-insight">{result.model_info?"Integrated outward heat only. Inward ambient and ground heat appear separately as gains in the energy ledger.":"Original legacy pathway values; they may not reconcile with the legacy recorded loss total."}</p>
      </CardContent></Card>
    </div>
    {result.model_info && Boolean(result.energy_balance?.length) && <EnergyBalance key={result.id} result={result}/>}
  </>;
}